Comm:
  namespace: pta
  images_domin: registry.cn-beijing.aliyuncs.com/lucentwang
  imagePullSecrets: registry-aliyun

Projects:
  pta: 
    - name: pta-gateway
      replicas: 3
      limits: 
        cpu: 1
        memory: 1Gi

    - name: pta-modules-analyze
      replicas: 2
      limits: 
        cpu: 1
        memory: 1Gi

    - name: pta-modules-business
      replicas: 2
      limits: 
        cpu: 1
        memory: 1Gi

    - name: pta-modules-contract
      replicas: 2
      limits: 
        cpu: 2
        memory: 2Gi

    - name: pta-modules-datacollection
      replicas: 2
      limits: 
        cpu: 1
        memory: 1Gi
      
    - name: pta-modules-disclosure
      replicas: 2
      limits: 
        cpu: 3
        memory: 3Gi

    - name: pta-modules-electric
      replicas: 2
      limits: 
        cpu: 1
        memory: 1Gi

    - name: pta-modules-file
      replicas: 2
      limits: 
        cpu: 1
        memory: 1Gi

    - name: pta-modules-guest-manage
      replicas: 2
      limits: 
        cpu: 1
        memory: 1Gi

    - name: pta-modules-job
      replicas: 2
      limits: 
        cpu: 1
        memory: 1Gi

    - name: pta-modules-weather
      replicas: 2
      limits: 
        cpu: 1.5
        memory: 2Gi

  uap: 
    name: uap
    replicas: 3
    limits: 
      cpu: 1
      memory: 1Gi

  MicroFront: 
    name: microfront
    replicas: 3
    limits: 
      cpu: 1
      memory: 1Gi
  

Secret:
  nacos: 
    area: "pro"
    nacos_url: "nacos-hs.middleware.svc.cluster.local:8848"
    group: "DEFAULT_GROUP"
  project: 
    - name: pta
      namespace: pta
      nacos_user: "pta"
      nacos_passwd: "PassW0rd"
    - name: uap
      namespace: uap
      nacos_user: "pta"
      nacos_passwd: "PassW0rd"
 
    
SVC: 
  uap: 
    name: uap
    targetPort: 8080
  pta: 
    name: pta-gateway
    targetPort: 8080
    
