Comm:
  namespace: pta
  images_domin: registry.cn-beijing.aliyuncs.com/lucentwang

Projects:
  - name: pta-gateway
    replicas: 1
    image: pta-gateway:latest
    port: 8080
  - name: pta-modules-analyze
    replicas: 1
    image: pta-modules-analyze:latest
    port: 8080
  - name: pta-modules-business
    replicas: 1
    image: pta-modules-business:latest
    port: 8080
  - name: pta-modules-contract
    replicas: 1
    image: pta-modules-contract:latest
    port: 8080
  - name: pta-modules-datacollection
    replicas: 1
    image: pta-modules-datacollection:latest
    port: 8080
  - name: pta-modules-disclosure
    replicas: 1
    image: pta-modules-disclosure:latest
    port: 8080
  - name: pta-modules-electric
    replicas: 1
    image: pta-modules-electric:latest
    port: 8080
  - name: pta-modules-file
    replicas: 1
    image: pta-modules-file:latest
    port: 8080
  - name: pta-modules-guest-manage
    replicas: 1
    image: pta-modules-guest-manage:latest
    port: 8080
  - name: pta-modules-job
    replicas: 1
    image: pta-modules-job:latest
    port: 8080
  - name: pta-modules-weather
    replicas: 1
    image: pta-modules-weather:latest
    port: 8080
  - name: uap 
    replicas: 3
    image: uap:latest
    port: 8080

MicroFront: 
  name: microfront
  replicas: 3
  image: microfront:latest
  port: 80
  nodePort: 32090
  

Config:
  nacos: 
    area: "pro"
    nacos_url: "nacos-hs.middleware.svc.cluster.local:8848"
    group: "DEFAULT_GROUP"
  project: 
    - name: pta
      namespace: pta
      nacos_user: "pta"
      nacos_passwd: "PassW0rd"
    - name: uap
      namespace: uap
      nacos_user: "pta"
      nacos_passwd: "PassW0rd"
 
    
SVC: 
  uap: 
    name: uap
    targetPort: 8080
  pta: 
    name: pta-gateway
    targetPort: 8080
    