Comm:
  namespace: pta
  images_domin: registry.cn-beijing.aliyuncs.com/lucentwang

Projects:
  pta: 
    - name: pta-gateway
      replicas: 1
      image: pta-gateway:latest

    - name: pta-modules-analyze
      replicas: 1
      image: pta-modules-analyze:latest

    - name: pta-modules-business
      replicas: 1
      image: pta-modules-business:latest

    - name: pta-modules-contract
      replicas: 1
      image: pta-modules-contract:latest

    - name: pta-modules-datacollection
      replicas: 1
      image: pta-modules-datacollection:latest
      
    - name: pta-modules-disclosure
      replicas: 1
      image: pta-modules-disclosure:latest

    - name: pta-modules-electric
      replicas: 1
      image: pta-modules-electric:latest

    - name: pta-modules-file
      replicas: 1
      image: pta-modules-file:latest

    - name: pta-modules-guest-manage
      replicas: 1
      image: pta-modules-guest-manage:latest

    - name: pta-modules-job
      replicas: 1
      image: pta-modules-job:latest

    - name: pta-modules-weather
      replicas: 1
      image: pta-modules-weather:latest

  uap: 
    name: uap
    replicas: 1
    image: uap:latest


MicroFront: 
  name: microfront
  replicas: 1
  image: microfront:latest
  nodePort: 32090
  

Config:
  nacos: 
    area: "pro"
    nacos_url: "nacos-hs.middleware.svc.cluster.local:8848"
    group: "DEFAULT_GROUP"
  project: 
    - name: pta
      namespace: pta
      nacos_user: "pta"
      nacos_passwd: "PassW0rd"
    - name: uap
      namespace: uap
      nacos_user: "pta"
      nacos_passwd: "PassW0rd"
 
    
SVC: 
  uap: 
    name: uap
    targetPort: 8080
  pta: 
    name: pta-gateway
    targetPort: 8080
    
