{{- range .Values.Projects.pta }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.Comm.namespace }}
spec:
  replicas: {{ .replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      imagePullSecrets:
        - name: {{ $.Values.Comm.imagePullSecrets }}
      containers:
        - name: {{ .name }}
          image: {{ $.Values.Comm.images_domin }}/{{ .name }}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: {{ .limits.cpu }}
              memory: {{ .limits.memory }}
            requests:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: area
              valueFrom:
                secretKeyRef:
                  name: pta
                  key: area
            - name: nacos_url
              valueFrom:
                secretKeyRef:
                  name: pta
                  key: nacos_url
            - name: nacos_user
              valueFrom:
                secretKeyRef:
                  name: pta
                  key: nacos_user
            - name: nacos_passwd
              valueFrom:
                secretKeyRef:
                  name: pta
                  key: nacos_passwd
            - name: namespace
              valueFrom:
                secretKeyRef:
                  name: pta
                  key: namespace
            - name: group
              valueFrom:
                secretKeyRef:
                  name: pta
                  key: group
---
{{- end }}
