apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Projects.uap.name }}
  namespace: {{ $.Values.Comm.namespace }}
spec:
  replicas: {{ .Values.Projects.uap.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: uap
  template:
    metadata:
      labels:
        app: uap
    spec:
      imagePullSecrets:
        - name: registry-aliyun
      containers:
        - name: uap
          image: {{ $.Values.Comm.images_domin }}/{{ .Values.Projects.uap.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: area
              valueFrom:
                secretKeyRef:
                  name: uap
                  key: area
            - name: nacos_url
              valueFrom:
                secretKeyRef:
                  name: uap
                  key: nacos_url
            - name: nacos_user
              valueFrom:
                secretKeyRef:
                  name: uap
                  key: nacos_user
            - name: nacos_passwd
              valueFrom:
                secretKeyRef:
                  name: uap
                  key: nacos_passwd
            - name: namespace
              valueFrom:
                secretKeyRef:
                  name: uap
                  key: namespace
            - name: group
              valueFrom:
                secretKeyRef:
                  name: uap
                  key: group
      restartPolicy: Always