apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.MicroFront.name }}
  namespace: {{ .Values.Comm.namespace }}
spec:
  selector:
    app: {{ .Values.MicroFront.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.MicroFront.nodePort }}
  type: NodePort
