{{- range .Values.Secret.project }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    name: tenguwang<tenguwang@163.com>
  labels:
    type: config
    project: {{ .name }}
  name: {{ .name }}
  namespace: {{ $.Values.Comm.namespace }}
type: Opaque
stringData:
  area: {{ $.Values.Secret.nacos.area }}
  nacos_url: {{ $.Values.Secret.nacos.nacos_url }}
  nacos_user: {{ .nacos_user }}
  nacos_passwd: {{ .nacos_passwd }}
  namespace: {{ .namespace }}
  group: {{ $.Values.Secret.nacos.group }}
---
{{ end }}
