{{- range .Values.SVC }}
{{ if ne .name "microfront" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-headless-svc
  namespace: {{ $.Values.Comm.namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .targetPort}}
---
{{ end }}
{{ end }}