apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Projects.MicroFront.name }}
  namespace: {{ .Values.Comm.namespace }}
spec:
  selector:
    app: {{ .Values.Projects.MicroFront.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.SVC.microfront.port }}
      targetPort: 80
  type: {{ .Values.SVC.microfront.type }}
